# Settings for the Makefile which define
# various things like the names, paths, etc pp
#
# 

# GRF Name, Version, Build type or date
# The name shown in OpenTTD's NewGRF selection window
GRF_NAME        = 2cc Train Set

# Filename part which indicates the development tar
GRF_NIGHTLYNAME = nightly

# The filename of the GRF without extension
FILENAME        = 2cctrainset

# extension of the source code files
# don't name it nfo but something else
PNFO_SUFFIX = pnfo

# Suffix of the pre-processed nfo file:
CPNFO_SUFFIX = cpnfo

# other relevant extensions. Normally it's not necessary to edit these
NFO_SUFFIX = nfo
GRF_SUFFIX = grf
TAR_SUFFIX = tar
BZ2_SUFFIX = bz2
ZIP_SUFFIX = zip
PCX_SUFFIX = pcx

# Build parameters and programmes
NFORENUM_FLAGS = -w 141
GRFCODEC_FLAGS = -e -p 2
TAR_FLAGS      = cf
ZIP_FLAGS      = -r
BZIP_FLAGS     = -k9f

# Programms for use in the makefile
NFORENUM = renum
GRFCODEC = grfcodec
TAR      = tar
ZIP      = zip
BZIP     = bzip2

# Paths defining the directory layout
# directory containing the sprites (pnfo and pcx files)
#
# Generally the structure is expected to look like this
# <main>
# |-sprites
# | |-nfo
# | | |-header.pnfo
# | | |-subdir
# | | | |-somefile.pnfo
# | | |-langdir
# | | | |-english.pnfo
# | |-pcx
# |   |-images.pcx
# |   |-subdir
# |     |-somefile.pcx
# |-docdir
# | |-readme.txt
# | |-license.txt
# | |-changelog.txt
# |-website
# |-scripts
# |-Makefile
# |-Makefile.config

SPRITEDIR   = sprites

# if you have scripts
SCRIPTDIR   = scripts

# directory containing your documentation
DOCDIR      = doc

# directory containing your website
WEBSITEDIR  = website

# directory containing the pnfo files (sub dir of spritedir?)
NFODIR      = $(SPRITEDIR)/nfo
PCXDIR      = $(SPRITEDIR)/pcx
MAINDIRS    = $(SPRITEDIR) $(SCRIPTDIR) $(DOCDIR) $(WEBDIR) $(BUNDLEDIR)

# Names of the subdirectories (if applicable). All pnfo
# files from there will be put into the final grf.
NFO_SUBDIRS = 2africa 3asia 4e-eu 5n-am 6s-am 7ocean 8scandinavia 9s-eu 10w-eu

# if they're the same as NFO_SUBDIRS, use
# PCXSUB_DIRS = $(NFO_SUBDIRS)
PCX_SUBDIRS = 

# The language directory. All pnfo files from there will be
# put into the final grf.
LANG_DIR    = strings

# Filenames to include in the grf in sprites/nfo
# HEADER goes first, FOOTER goes last. The others are 
# placed behind header and before engines and language strings.
# Don't add the suffix
HEADER      = 00header
OTHERS      = 01wagons 00sounds 11maglev
FOOTER      = regsel

# Documentation files with relative path. Usually they should be in $(DOCDIR).
LICENSEFILE = $(DOCDIR)/license.txt
READMEFILE  = $(DOCDIR)/readme.txt
CHANGELOG   = $(DOCDIR)/changelog.txt

DOCUMENTATION = $(LICENSEFILE) $(READMEFILE) $(CHANGELOG)

# Define how the displayed name and the filename of the bundled grf shall look like:
GRF_TITLE    = $(GRF_NAME) $(shell [ -n "$(REPO_TAGS)" ] && echo $(REPO_TAGS)$(GRF_MODIFIED) || echo $(GRF_NIGHTLYNAME)-r$(GRF_REVISION)$(GRF_MODIFIED))

BUILDFILENAME = $(FILENAME)-$(shell [ -n "$(REPO_TAGS)" ] && echo $(REPO_TAGS)$(GRF_MODIFIED) || echo $(GRF_NIGHTLYNAME))
DIR_NAME      = $(BUILDFILENAME)

TAR_FILENAME   = $(BUILDFILENAME).$(TAR_SUFFIX)
BZIP_FILENAME  = $(BUILDFILENAME).$(BZ2_SUFFIX)
ZIP_FILENAME   = $(BUILDFILENAME).$(ZIP_SUFFIX)
NFO_FILENAME   = $(SPRITEDIR)/$(addsuffix .$(NFO_SUFFIX),$(FILENAME))
CPNFO_FILENAME = $(SPRITEDIR)/$(addsuffix .$(CPNFO_SUFFIX),$(FILENAME))
GRF_FILENAME   = $(addsuffix .$(GRF_SUFFIX),$(FILENAME))

# Files to include in a release (e.g. to pack into tar, zip, files)
BUNDLE_FILES  = $(GRF_FILENAME) $(DOCUMENTATION)

# Adding the proper paths to the files which comprise the newgrf
# Normally this need not be changed
HEADER_FILE   = $(addsuffix .$(PNFO_SUFFIX),$(NFODIR)/$(HEADER))
FOOTER_FILE   = $(shell [ -n "$(FOOTER)" ] && echo "$(addsuffix .$(PNFO_SUFFIX),$(NFODIR)/$(FOOTER))")
OTHER_FILES   = $(shell [ -n "$(OTHERS)" ] && echo "$(addsuffix .$(PNFO_SUFFIX),$(addprefix $(NFODIR)/,$(OTHERS)))")
LANG_FILES    = $(shell [ -n "$(LANG_DIR)" ] && echo "$(wildcard $(NFODIR)/$(LANG_DIR)/*.$(PNFO_SUFFIX))")
NFO_SUBFILES  = $(shell [ -n "$(NFO_SUBDIRS)" ] && echo "$(foreach dir,$(NFO_SUBDIRS),$(wildcard $(NFODIR)/$(dir)/*.$(PNFO_SUFFIX)))")
PCX_FILES     = $(shell [ -n "$(PCX_SUBDIRS)" ] && echo "$(foreach dir,$(PCX_SUBDIRS),$(wildcard $(PCX_DIR)/$(PCX_SUBDIRS)/*.$(PCX_SUFFIX)))")
