# Settings for the Makefile which define
# various things like the names, paths, etc pp
#
# 

# GRF Name, Version, Build type or date
GRF_NAME     = 2cc Train Set
GRF_VERSION  = 1.0.1
GRF_BUILD    = pre-release
NAME 	     = $(GRF_FILENAME)
GRF_TITLE    = $(GRF_NAME) (r$(GRF_REVISION), $(GRF_BUILD))

# The filename of the GRF
GRF_FILENAME = 2cc_trainset

# Build parameters and programmes
NFORENUM_FLAGS = -w 141
GRFCODEC_FLAGS = -e -p 2

NFORENUM = renum
GRFCODEC = grfcodec

# Paths defining the directory layout
SPRITEDIR   = ./sprites
SCRIPTDIR   = ./scripts
DOCDIR      = ./doc
WEBDIR      = ./website
NFODIR      = $(SPRITEDIR)/nfo
MAINDIRS    = $(SPRITEDIR) $(SCRIPTDIR) $(DOCDIR) $(WEBDIR)

# Names of the subdirectories for the single regions. All nfo
# files from there will be put into the final grf.
REGION_DIRS = 2africa 3asia 4e-eu 5n-am 6s-am 7ocean 8scandinavia 9s-eu 10w-eu

# The language directory. All nfo files from there will be
# put into the final grf.
LANG_DIR    = strings

# Filenames to include in the grf in sprites/nfo
# HEADER goes first, FOOTER goes last. The others are 
# placed behind header and before engines and language strings.
HEADER      = 00header
OTHERS      = 01wagons 00sounds
FOOTER      = regsel

