# Settings for the Makefile which define
# various things like the names, paths, etc pp
#
# 

# GRF Name, Version, Build type or date
GRF_NAME        = 2cc Train Set
GRF_NIGHTLYNAME = nightly

# The filename of the GRF
FILENAME        = 2cctrainset
NAME 	        = $(FILENAME)


NFO_SUFFIX = nfo
GRF_SUFFIX = grf
PNFO_SUFFIX = nfo.pre

# Build parameters and programmes
NFORENUM_FLAGS = -w 141
GRFCODEC_FLAGS = -e -p 2

NFORENUM = renum
GRFCODEC = grfcodec

# Paths defining the directory layout
SPRITEDIR   = ./sprites
SCRIPTDIR   = ./scripts
DOCDIR      = ./doc
WEBDIR      = ./website
NFODIR      = $(SPRITEDIR)/nfo
MAINDIRS    = $(SPRITEDIR) $(SCRIPTDIR) $(DOCDIR) $(WEBDIR)

# Names of the subdirectories for the single regions. All nfo
# files from there will be put into the final grf.
SUB_DIRS = 2africa 3asia 4e-eu 5n-am 6s-am 7ocean 8scandinavia 9s-eu 10w-eu

# The language directory. All nfo files from there will be
# put into the final grf.
LANG_DIR    = strings

# Filenames to include in the grf in sprites/nfo
# HEADER goes first, FOOTER goes last. The others are 
# placed behind header and before engines and language strings.
HEADER      = 00header.nfo
OTHERS      = 01wagons.nfo 00sounds.nfo
FOOTER      = regsel.nfo

# Define how the displayed name and the filename of the bundled grf shall look like:
GRF_BUILDNAME= $(shell [ -n "$(REPO_TAGS)" ] && echo $(REPO_TAGS)$(GRF_MODIFIED) || echo $(GRF_NIGHTLYNAME)-r$(GRF_REVISION)$(GRF_MODIFIED))

GRF_TITLE    = $(GRF_NAME) $(GRF_BUILDNAME)

TAR_FILENAME  = $(FILENAME)-$(GRF_BUILDNAME).tar
NFO_FILENAME  = $(addsuffix .$(NFO_SUFFIX), $(FILENAME))
PNFO_FILENAME = $(addsuffix .$(PNFO_SUFFIX),$(FILENAME))
GRF_FILENAME  = $(addsuffix .$(GRF_SUFFIX), $(FILENAME))

# Files to include in a release
FILES_BUNDLE = $(GRF_FILENAME) $(DOCDIR)/license.txt $(DOCDIR)/readme.txt
